trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: ls -la
  displayName: Debug files

- script: npm install
  displayName: Install dependencies

- script: node app.js
  displayName: Run App
