trigger:
- main

pool:
  name: Default

steps:
- script: echo "Building project..."
  displayName: 'Build Step'

- script: echo "Deploying project..."
  displayName: 'Deploy Step'

# Create a file to publish
- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)
    echo "Hi , Iam from future" > $(Build.ArtifactStagingDirectory)/output.txt
  displayName: 'Create Artifact File'

# Publish artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
